language: node_js
node_js: 5.9.1

before_install:
- npm install hexo -g

- openssl aes-256-cbc -K $encrypted_f901e14975c5_key -iv $encrypted_f901e14975c5_iv
  -in .travis/travis_ci.enc -out ~/.ssh/travis_ci -d

# Set the permission of the key
- chmod 600 ~/.ssh/travis_ci
# Start SSH agent
- eval $(ssh-agent)
# Add the private key to the system
- ssh-add ~/.ssh/travis_ci
# Copy SSH config
- cp .travis/ssh_config ~/.ssh/config
# Set Git config
- git config --global user.name "travis_robot"
- git config --global user.email "travis_robot@thinkinnight.com"

script:
- hexo generate
- hexo deploy
branches:
  only:
  - master
